Add background documentation to the Readme.
ScottLogic/blog pull request #116
Opened 2023-11-15 16:31 UTC by ithake

Please add a direct link to your post here:

https://<your-username>.github.io/blog/<post-url>

Have you (please tick each box to show completion):

 - [ ] Added your blog post to a single category?
 - [ ] Added a brief summary for your post? Summaries should be roughly two sentences in length and give potential readers a good idea of the contents of your post.
 - [ ] Checked that the build passes?
 - [ ] Checked your spelling (you can use `npm spellcheck` if that's your thing)
 - [ ] Ensured that your author profile contains a profile image, and a brief description of yourself? (make it more interesting than just your job title!)
 - [ ] Optimised any images in your post? They should be less than 100KBytes as a general guide.

Posts are approved based on their category. replace `(at)` with `@` to notify them!

 - Tech - Colin Eberhardt - (at)ColinEberhardt
 - Cloud - Colin Eberhardt - (at)ColinEberhardt
 - Delivery - Matt Phillips - (at)scottlogicmphillips
 - UX - Graham Odds - (at)godds
 - People - Graham Odds - (at)godds
 - Testing - Laurence Pisani - (at)lpisani-SL

2023-11-15 16:34 UTC, ithake commented on README.md
> +- [Ruby][ruby-downloads].
"and in the darkness bind them."

2023-11-15 16:44 UTC, ithake commented on README.md
> +[confluence-getting-started]: https://scottlogic.atlassian.net/wiki/spaces/INT/pages/3577479175/Getting+started+with+the+Scott+Logic+blog
FYI - this is the new link - previous link: https://scottlogic.atlassian.net/wiki/spaces/INT/pages/219054172/Getting+started+with+the+blog was broken.

2023-11-16 09:26 UTC, ColinEberhardt requested changes
Thanks @ithake some very helpful updates - one small request also.

2023-11-16 09:26 UTC, ColinEberhardt commented on README.md
> +and use the [blog tool][blog-tool-endpoint] for an easy way to publish blog posts.
yikes - the 'blog tool' hasn't been supported for a while now, and isn't mentioned in our confluence pages. Can you please remove references to it, and I'll look at decommissioning it properly.

2023-11-16 09:27 UTC, ithake commented on README.md
> +and use the [blog tool][blog-tool-endpoint] for an easy way to publish blog posts.
Will do.  (That also answers a few questions we had!).

2023-11-16 09:31 UTC, ithake commented on README.md
> +and use the [blog tool][blog-tool-endpoint] for an easy way to publish blog posts.
@ColinEberhardt  - given that the blog tool link to https://cz90l8ad7e.execute-api.eu-west-2.amazonaws.com/production/ still works - does that mean as a company we're being billed for keeping it running on AWS?

2023-11-16 16:02 UTC, ColinEberhardt approved these changes

2023-11-16 16:04 UTC, merged

2023-11-16 16:04 UTC, ColinEberhardt commented
thanks @ithake

2023-11-16 16:04 UTC, ColinEberhardt commented on README.md
> +and use the [blog tool][blog-tool-endpoint] for an easy way to publish blog posts.
serverless ;-)