Refactor includes:  author-summary, author-link
ScottLogic/blog pull request #124
Opened 2023-11-17 16:46 UTC by ithake

Original goal was to allow the contents of https://blog.scottlogic.com/2019/07/23/Testing-WebSockets-for-beginners.html
to 
- `my colleague {% include author-link.html data-id="hwilliams" %},`

instead of 
- `my colleague [Herb Williams]({{site.baseurl}}/hwilliams),`

So created **_includes/author-link.html**.

On consideration, it seemed a better design to keep markdown content and layout includes separate, so didn't apply to the original post. However, the associated refactoring to use parameters with the new include file reduced some boiler plate from the original files, so seemed worth keeping and doing the related author-summary.html as well.

On testing the changes I noticed that, when you reduce the width of the display, the alternative list of contributors was being rendered with a space before the comma in the list, so fixed that as well.

Before:
<img width="179" alt="author-link-commas-before" src="https://github.com/ScottLogic/blog/assets/5435709/e7e14b10-1a03-4fdf-9a70-8ede64d8124f">

After:
<img width="182" alt="author-link-commas-after" src="https://github.com/ScottLogic/blog/assets/5435709/7ce5c78f-0cbf-486f-9809-cc27f5d1b8c5">

Please add a direct link to your post here:

https://<your-username>.github.io/blog/<post-url>

Have you (please tick each box to show completion):

 - [ ] Added your blog post to a single category?
 - [ ] Added a brief summary for your post? Summaries should be roughly two sentences in length and give potential readers a good idea of the contents of your post.
 - [ ] Checked that the build passes?
 - [ ] Checked your spelling (you can use `npm spellcheck` if that's your thing)
 - [ ] Ensured that your author profile contains a profile image, and a brief description of yourself? (make it more interesting than just your job title!)
 - [ ] Optimised any images in your post? They should be less than 100KBytes as a general guide.

Posts are approved based on their category. replace `(at)` with `@` to notify them!

 - Tech - Colin Eberhardt - (at)ColinEberhardt
 - Cloud - Colin Eberhardt - (at)ColinEberhardt
 - Delivery - Matt Phillips - (at)scottlogicmphillips
 - UX - Graham Odds - (at)godds
 - People - Graham Odds - (at)godds
 - Testing - Laurence Pisani - (at)lpisani-SL

2023-11-21 10:28 UTC, ithake commented
Will rebase and mark ready for review once https://github.com/ScottLogic/blog/pull/125 is merged.

2023-11-27 16:18 UTC, ColinEberhardt commented on _layouts/default_post.html
> +            {% include author-link.html author-id=contributorId %}
is this a premature refactor, given that `author-link` is used just once and is only a few lines long?

2023-11-27 16:18 UTC, ColinEberhardt commented
Thanks for spotting that issue, and fixing @ithake - I do have one question on the implementation.

2023-12-08 08:34 UTC, ColinEberhardt requested changes
see outstanding question ...

2023-12-08 10:39 UTC, ithake commented on _layouts/default_post.html
> +            {% include author-link.html author-id=contributorId %}
I think it's good refactor, but it's a judgement call, and happy to be over-ruled.

As per the comments, at an earlier stage the include `author-link` was used twice, because it was part of my fix to a broken link to an author within a blog post.  Why I felt it was worth keeping in as a separate "thing" is that, although in technical functionality it's a very small thing, in the context of a blog post, it seemed that "link to another blog author"  was a meaningful chunk of domain functionality, and so it's an opportunity to have the building blocks of the code align with that of the domain for easier reading of the project.

Not something that I was aware of at the time. but as part of screen reader testing, there's a comment that links need better naming/labelling.  That points to a future changes that would alter code around the author link but leave the surrounding author-summary functionality unchanged.  In turn, that's like a nudge towards this being a natural "seam" to split apart the functionality so that you have an unchanged file and a changed file in that future change.

Again, this is an early pass at refactoring jekyll/liquid so my instincts on when to refactor may be off, so happy to change if you think the new structure would be confusing to people.

Finally, there's no getting round the fact that it's adding a new file to the build process for minimal technical benefit.  That's why I took the trouble to run some timed builds to try and confirm there was no meaningful impact.
Jekyll documentation suggests moving to tag `render` in place of `include` would offer some build-time improvements, but that seemed even further out of scope.

2023-12-08 15:42 UTC, merged