New Blog post on measuring energy consumption of hardware
ScottLogic/blog pull request #136
Opened 2023-12-05 15:03 UTC by mgriffin-scottlogic

Please add a direct link to your post here:

https://mgriffin-scottlogic.github.io/blog/2023/12/05/conscientious-computing-accurately-measuring-the-energy-consumption-of-hardware.html

Have you (please tick each box to show completion):

 - [x] Added your blog post to a single category?
 - [x] Added a brief summary for your post? Summaries should be roughly two sentences in length and give potential readers a good idea of the contents of your post.
 - [x] Checked that the build passes?
 - [x] Checked your spelling (you can use `npm spellcheck` if that's your thing)
 - [x] Ensured that your author profile contains a profile image, and a brief description of yourself? (make it more interesting than just your job title!)
 - [x] Optimised any images in your post? They should be less than 100KBytes as a general guide.

Posts are approved based on their category. replace `(at)` with `@` to notify them!

 - Tech - Colin Eberhardt - @ColinEberhardt

Also @cronky to review/decide on when to post?

2023-12-06 08:46 UTC, mgriffin-scottlogic commented
@ColinEberhardt Oliver has reviewed and approved so this is ready to merge.

2023-12-08 08:39 UTC, ColinEberhardt requested changes
Thanks for this excellent post @mgriffin-scottlogic - just one small comment on the markup. If you can fix that, update the post date, then ping me on Teams I'll get this merged straight away!

2023-12-08 08:39 UTC, ColinEberhardt commented on _posts/2023-12-05-conscientious-computing-accurately-measuring-the-energy-consumption-of-hardware.md
> +# Power Monitors
These should be h2 headers, i.e. `##`

2023-12-08 09:06 UTC, ColinEberhardt approved these changes

2023-12-08 09:06 UTC, merged