Blog_Testing GenerativeAI Chatbot Models
ScottLogic/blog pull request #265
Opened 2024-10-30 09:59 UTC by Shikha-Nandal

Please add a direct link to your post here:

https://shikha-nandal.github.io/blog/2024/10/28/Testing-GenerativeAI-Chatbots.html

Have you (please tick each box to show completion):

 - [X] Added your blog post to a single category?
 - [X] Added a brief summary for your post? Summaries should be roughly two sentences in length and give potential readers a good idea of the contents of your post.
 - [X] Checked that the build passes?
 - [X] Checked your spelling (you can use `npm install` followed by `npx mdspell "**/{FILE_NAME}.md" --en-gb -a -n -x -t` if that's your thing)
 - [X] Ensured that your author profile contains a profile image, and a brief description of yourself? (make it more interesting than just your job title!)
 - [X] Optimised any images in your post? They should be less than 100KBytes as a general guide.

Posts are reviewed / approved by your Regional Tech Lead.

2024-10-30 10:18 UTC, joshi-sonali requested changes
Looks good overall, a few minor comments

2024-10-30 10:18 UTC, joshi-sonali commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +- Accuracy: How correct the outputs are based on expected results.
This is not showing as a list when published.

2024-10-30 10:18 UTC, joshi-sonali commented on _posts/2024-09-01-Evolving-with-AI-From-Traditional-Testing-to-Model-Evaluation-I.md
> +---
This file can be removed since it's a post that has already been published.

2024-10-30 10:18 UTC, joshi-sonali commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**5. Continuous learning and Evolution:** AI systems are designed to continuously learn from user interactions and evolve over time. This dynamic nature poses a significant challenge for testing, as
Just a minor thing - could you break the end of this paragraph down so that it's not 1 long sentence?

2024-10-30 11:43 UTC, Shikha-Nandal commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +- Accuracy: How correct the outputs are based on expected results.
See if it looks better now

2024-10-30 11:44 UTC, Shikha-Nandal commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**5. Continuous learning and Evolution:** AI systems are designed to continuously learn from user interactions and evolve over time. This dynamic nature poses a significant challenge for testing, as
See if it looks better now

2024-10-30 16:18 UTC, lhancock-scottlogic reviewed
Looks really good, I like that you've included multiple testing frameworks and included resources for them both. Just got a few comments for you :)

2024-10-30 16:18 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**2. Learning Ability:** Through machine learning algorithms, these models have ability to continuously learn from interactions and to improve their responses over time. By analysing vast amounts of
```suggestion
**2. Learning Ability:** Through machine learning algorithms, these models have ability to continuously learn from interactions and to improve their responses over time. By analysing vast amounts of data and feedback from users, AI can refine its understanding and prediction capabilities and is hence very adaptable to new patterns, trends and user behaviours; making it more accurate, reliable and effective in dynamic environments. 
```

2024-10-30 16:18 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +This technology is revolutionising multiple industries like Healthcare, Entertainment, Marketing, Finance by enhancing creativity and efficiency. And hence there is the need for its effective testing
```suggestion
This technology is revolutionising multiple industries like Healthcare, Entertainment, Marketing, and Finance by enhancing creativity and efficiency. And hence there is the need for its effective testing to ensure that these models meet the desired standards of performance and user engagement. 
```

2024-10-30 16:18 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**1. Non-Deterministic Responses:** GenAI chatbot models exhibit non-deterministic behaviour, meaning that they can generate completely different responses to the exact same input, under exact same c
```suggestion
**1. Non-Deterministic Responses:** GenAI chatbot models exhibit non-deterministic behaviour, meaning that they can generate completely different responses to the exact same input, under the exact same conditions. These variations in responses are not necessarily errors, but mere deviations from previous behaviour, making it harder to define what constitutes a "correct" and “expected” response. 
```

2024-10-30 16:18 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +Hence GenAI model testing require sophisticated techniques such as probabilistic testing, where multiple iterations of the same test case are executed to assess the overall performance of the model.
```suggestion
Hence GenAI model testing requires sophisticated techniques such as probabilistic testing, where multiple iterations of the same test case are executed to assess the overall performance of the model. 
```

2024-10-30 16:18 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**Simulate Real User Behaviour** Use diverse and realistic test data to emulate actual user interactions. This involves:
This, and the headings below it, need a dash, colon or line break to make them a little more readable as headings :)

2024-10-30 16:18 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +*By following a structured approach and using these tools, organisations can effectively test and refine GenAI chatbot models, ensuring high-quality outputs.*
How come this is in italics?

2024-10-31 08:47 UTC, Shikha-Nandal commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**1. Non-Deterministic Responses:** GenAI chatbot models exhibit non-deterministic behaviour, meaning that they can generate completely different responses to the exact same input, under exact same c
Updated as suggested.

2024-10-31 08:51 UTC, Shikha-Nandal commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**Simulate Real User Behaviour** Use diverse and realistic test data to emulate actual user interactions. This involves:
please see if it looks better now

2024-10-31 11:08 UTC, lhancock-scottlogic commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**Simulate Real User Behaviour** Use diverse and realistic test data to emulate actual user interactions. This involves:
Sorry, I don't think my comment was very clear - what I meant was that the headings (Simulate Real User Behaviour, Focus on Conversation Flow) have no separation from the content that follows it. So they may need some punctuation to separate the headings from the content, i.e:

```suggestion
**Simulate Real User Behaviour**: Use diverse and realistic test data to emulate actual user interactions. This involves: 
```

2024-10-31 12:11 UTC, joshi-sonali approved these changes

2024-10-31 12:51 UTC, Shikha-Nandal commented on _posts/2024-10-28-Testing-GenerativeAI-Chatbots.md
> +**Simulate Real User Behaviour** Use diverse and realistic test data to emulate actual user interactions. This involves:
Got it.. used "-" instead of ":" coz I have ":" already in the sentence later on.. Please if it look okay now

2024-11-01 10:38 UTC, lhancock-scottlogic approved these changes

2024-11-01 11:34 UTC, merged