Xin testing blog PR
ScottLogic/blog pull request #92
Opened 2023-10-30 16:43 UTC by dscarborough-scottlogic

Please add a direct link to your post here:

https://xchenscottlogic.github.io/blog/2023/10/29/testing-LLM-based-applications-strategy-and-challenges.html

Have you (please tick each box to show completion):

 - [x] Added your blog post to a single category?
 - [x] Added a brief summary for your post? Summaries should be roughly two sentences in length and give potential readers a good idea of the contents of your post.
 - [x] Checked that the build passes?
 - [x] Checked your spelling (you can use `npm spellcheck` if that's your thing)
 - [x] Ensured that your author profile contains a profile image, and a brief description of yourself? (make it more interesting than just your job title!)
 - [x] Optimised any images in your post? They should be less than 100KBytes as a general guide.

Posts are approved based on their category. replace `(at)` with `@` to notify them!

 - Tech - Colin Eberhardt - @ColinEberhardt
 - Cloud - Colin Eberhardt - (at)ColinEberhardt
 - Delivery - Matt Phillips - (at)scottlogicmphillips
 - UX - Graham Odds - (at)godds
 - People - Graham Odds - (at)godds
 - Testing - Laurence Pisani - @lpisani-SL

2023-11-06 08:53 UTC, ColinEberhardt requested changes
Thanks - a really interesting post. Added a few specific comments, also a couple of other points ...

Some of your example BDD files are quite long, perhaps edit them down to smaller set of examples?

For some of the BDD tests I am unsure how they are actually implemented, for example, they verify that the output "should be readable", the "response time should be reasonable", the response "should be appropriate"

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Researchers commonly utilise standard metrics to assess traditional language models. These metrics include Perplexity (PPL), BLEU, and ROUGE. However, these metrics are not typically applicable for e
>  Perplexity (PPL), BLEU, and ROUGE

Could you provide links to these?

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Researchers commonly utilise standard metrics to assess traditional language models. These metrics include Perplexity (PPL), BLEU, and ROUGE. However, these metrics are not typically applicable for e
> these metrics are not typically applicable for evaluating applications in production that utilise an LLM as a third-party service.

that's an interesting point - why is that?

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +In this section, I will present the testing methodologies by using our customised chatbot, Scottbot, as an example. Scottbot is a Scott Logic domain-specific chatbot powered by GPT technology. It has
>  Scott Logic’s internal Confluence

Probably worth expanding on this - it has access to our intranet that is our internal knowledge-base

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +As we use pytest as the automation framework, pytest-bdd is a natural choice to give us a BDD style for all of our scenarios. As Scottbot is deployed on Azure, automated tests can be executed through
> pytest-bdd

link please!

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Based on Generative AI's non-deterministic feature, we can't do the exact match for the test results. A good solution to solve this issue is to introduce the LangChain string evaluators which uses a
> Based on Generative AI's non-deterministic feature

It's probably worth expanding on this - I'm not sure it is common knowledge that reducing temperature to zero still resuts in variability in the output

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +It ensures that the information provided by LLM applications aligns with real-world facts. Hallucination is a weakness of LLM. As a result, accuracy is crucial, particularly in customised application
Is it worth pointing out here that using the correct source is quite critical for Scottbot? We need to ensure that it chooses between Confluence and the internet wisely!

2023-11-06 08:53 UTC, ColinEberhardt commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +![Test_Scottbot_3_2.png]({{ site.github.url }}/uploads/Test_Scottbot_3_2.png)
How do you assert that the output "should be readable"

2023-11-07 16:23 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +![Test_Scottbot_3_2.png]({{ site.github.url }}/uploads/Test_Scottbot_3_2.png)
For the time being, it is a human verification process to check the readability. We may want to check if the contents contain any rubbish code, like consequent wild card characters in an automation way.

2023-11-07 16:24 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +It ensures that the information provided by LLM applications aligns with real-world facts. Hallucination is a weakness of LLM. As a result, accuracy is crucial, particularly in customised application
Updated.

2023-11-07 16:24 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +As we use pytest as the automation framework, pytest-bdd is a natural choice to give us a BDD style for all of our scenarios. As Scottbot is deployed on Azure, automated tests can be executed through
Updated.

2023-11-07 16:24 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +In this section, I will present the testing methodologies by using our customised chatbot, Scottbot, as an example. Scottbot is a Scott Logic domain-specific chatbot powered by GPT technology. It has
Updated.

2023-11-07 16:24 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Researchers commonly utilise standard metrics to assess traditional language models. These metrics include Perplexity (PPL), BLEU, and ROUGE. However, these metrics are not typically applicable for e
Updated.

2023-11-07 16:24 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Researchers commonly utilise standard metrics to assess traditional language models. These metrics include Perplexity (PPL), BLEU, and ROUGE. However, these metrics are not typically applicable for e
Updated.

2023-11-07 16:32 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Based on Generative AI's non-deterministic feature, we can't do the exact match for the test results. A good solution to solve this issue is to introduce the LangChain string evaluators which uses a
We set temperature to zero but my observation is that each time Scottbot still gives various responses, based on the question it received.  I looked on the internet and it is said zero temperature means completely deterministic. I am confused.

2023-11-07 16:51 UTC, XChenscottlogic commented on _posts/2023-10-29-testing-LLM-based-applications-strategy-and-challenges.markdown
> +Based on Generative AI's non-deterministic feature, we can't do the exact match for the test results. A good solution to solve this issue is to introduce the LangChain string evaluators which uses a
Updated.

2023-11-14 08:46 UTC, merged